### ISSUE TITLE
Group

### ISSUE THREAD

**Issue by nicklasb** [Julian/Seep#2]
I found it a bit difficult to express myself at the wiki without trampling all over the existing discussion, so I created a seep-devel google group for discussing its development. I'll happily transfer the ownership of the group to you guys if you think a group there is a good thing.

I posted a message there with some ideas.
https://groups.google.com/forum/#!forum/seep-devel

**Comment by Julian** [comment]
Awesome! Glad you're taking an interest. I'll have a look.
